package model;

public class Accidents {

//  AccidentId INT AUTO_INCREMENT,
//  X DOUBLE,
//  Y DOUBLE,
//  SeverityCode INT,
//  CollisionType VARCHAR(255),
//  PersonCount INT,
//  PedCount INT,
//  PedCycCount INT,
//  VehCount INT,


  protected int accidentId;
  protected Double xLoc;
  protected Double yLoc;
  protected int severityCode;
  protected String collisionType;
  protected int personCount;
  protected int pedCount;
  protected int pedCycCount;
  protected int vehCount;

  // This constructor can be used for reading records from MySQL, where we have all fields,
  // including the accidentId.
  public Accidents(int accidentId, Double xLoc, Double yLoc, int severityCode, String collisionType, int personCount, int pedCount, int pedCycCount, int vehCount) {
    this.accidentId = accidentId;
    this.xLoc = xLoc;
    this.yLoc = yLoc;
    this.severityCode = severityCode;
    this.collisionType = collisionType;
    this.personCount = personCount;
    this.pedCount = pedCount;
    this.pedCycCount = pedCycCount;
    this.vehCount = vehCount;
  }

  // This constructor can be used for reading records from MySQL, where we only have the postId,
  // such as a foreign key reference to PostId.
  // Given PostId, we can fetch the full BlogPost record.
  public Accidents(int accidentId) {
    this.accidentId = accidentId;
  }


  // This constructor can be used for creating new records, where the accidentId may not be
  // assigned yet since it is auto-generated by MySQL.
  public Accidents(Double xLoc, Double yLoc, int severityCode, String collisionType, int personCount, int pedCount, int pedCycCount, int vehCount) {
    this.xLoc = xLoc;
    this.yLoc = yLoc;
    this.severityCode = severityCode;
    this.collisionType = collisionType;
    this.personCount = personCount;
    this.pedCount = pedCount;
    this.pedCycCount = pedCycCount;
    this.vehCount = vehCount;
  }


  public int getAccidentId() {
    return accidentId;
  }

  public void setAccidentId(int accidentId) {
    this.accidentId = accidentId;
  }

  public Double getxLoc() {
    return xLoc;
  }

  public void setxLoc(Double xLoc) {
    this.xLoc = xLoc;
  }

  public Double getyLoc() {
    return yLoc;
  }

  public void setyLoc(Double yLoc) {
    this.yLoc = yLoc;
  }

  public int getSeverityCode() {
    return severityCode;
  }

  public void setSeverityCode(int severityCode) {
    this.severityCode = severityCode;
  }

  public String getCollisionType() {
    return collisionType;
  }

  public void setCollisionType(String collisionType) {
    this.collisionType = collisionType;
  }

  public int getPersonCount() {
    return personCount;
  }

  public void setPersonCount(int personCount) {
    this.personCount = personCount;
  }

  public int getPedCount() {
    return pedCount;
  }

  public void setPedCount(int pedCount) {
    this.pedCount = pedCount;
  }

  public int getPedCycCount() {
    return pedCycCount;
  }

  public void setPedCycCount(int pedCycCount) {
    this.pedCycCount = pedCycCount;
  }

  public int getVehCount() {
    return vehCount;
  }

  public void setVehCount(int vehCount) {
    this.vehCount = vehCount;
  }
}
