package model;

public class FavoriteLocations {

//  FavoriteLocId INT AUTO_INCREMENT,
//  UserName VARCHAR(255),

  protected int favoriteLocId;
  protected String userName;

  // This constructor can be used for reading records from MySQL, where we have all fields,
  // including the favoriteLocId.
  public FavoriteLocations(int favoriteLocId, String userName) {
    this.favoriteLocId = favoriteLocId;
    this.userName = userName;
  }

  // This constructor can be used for reading records from MySQL, where we only have the favoriteLocId,
  // such as a foreign key reference to favoriteLocId.
  // Given favoriteLocId, we can fetch the full FavoriteLocations record.
  public FavoriteLocations(int favoriteLocId) {
    this.favoriteLocId = favoriteLocId;
  }


  // This constructor can be used for creating new records, where the favoriteLocId may not be
  // assigned yet since it is auto-generated by MySQL.
  public FavoriteLocations(String userName) {
    this.userName = userName;
  }


  public int getFavoriteLocId() {
    return favoriteLocId;
  }

  public void setFavoriteLocId(int favoriteLocId) {
    this.favoriteLocId = favoriteLocId;
  }

  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }
}
