package model;

public class FavoriteParking {

//  FavoriteParkingId INT AUTO_INCREMENT,
//  ParkingId INT,
//  UserName VARCHAR(255),


  protected int favoriteParkingId;
  protected int parkingId;
  protected String userName;


  // This constructor can be used for reading records from MySQL, where we have all fields,
  // including the favoriteParkingId.
  public FavoriteParking(int favoriteParkingId, int parkingId, String userName) {
    this.favoriteParkingId = favoriteParkingId;
    this.parkingId = parkingId;
    this.userName = userName;
  }

  // This constructor can be used for reading records from MySQL, where we only have the favoriteParkingId,
  // such as a foreign key reference to favoriteParkingId.
  // Given favoriteParkingId, we can fetch the full FavoriteParking record.
  public FavoriteParking(int favoriteParkingId) {
    this.favoriteParkingId = favoriteParkingId;
  }


  // This constructor can be used for creating new records, where the favoriteParkingId may not be
  // assigned yet since it is auto-generated by MySQL.
  public FavoriteParking(int parkingId, String userName) {
    this.parkingId = parkingId;
    this.userName = userName;
  }

  public int getFavoriteParkingId() {
    return favoriteParkingId;
  }

  public void setFavoriteParkingId(int favoriteParkingId) {
    this.favoriteParkingId = favoriteParkingId;
  }

  public int getParkingId() {
    return parkingId;
  }

  public void setParkingId(int parkingId) {
    this.parkingId = parkingId;
  }

  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }
}
