package model;

import java.sql.Date;

public class PayStations {

//  PayStationId INT AUTO_INCREMENT,
//  X DOUBLE,
//  Y DOUBLE,
//  Neighborhood VARCHAR(50),
//  SubArea VARCHAR(50),
//  Side VARCHAR(2),
//  UnitDescription VARCHAR(255),
//  PayByPhone INT,
//  WeekDayRate_1Hour DOUBLE,
//  WeekDayRate_2Hour DOUBLE,
//  WeekDayRate_3Hour DOUBLE,
//  SaturdayRate_1Hour DOUBLE,
//  SaturdayRate_2Hour DOUBLE,
//  SaturdayRate_3Hour DOUBLE,
//  SaturdayStartTime Timestamp,
//  SaturdayEndTime Timestamp DEFAULT CURRENT_TIMESTAMP,


  protected int payStationId;
  protected Double xLoc;
  protected Double yLoc;
  protected String neighborhood;
  protected String subArea;
  protected String side;
  protected String unitDescription;
  protected int payByPhone;
  protected Double weekDayRate1Hour;
  protected Double weekDayRate2Hour;
  protected Double weekDayRate3Hour;
  protected Double SaturdayRate1Hour;
  protected Double SaturdayRate2Hour;
  protected Double SaturdayRate3Hour;
  protected Date saturdayStartTime;
  protected Date saturdayEndTime;



  // This constructor can be used for reading records from MySQL, where we have all fields,
  // including the payStationId.
  public PayStations(int payStationId, Double xLoc, Double yLoc, String neighborhood, String subArea, String side, String unitDescription, int payByPhone, Double weekDayRate1Hour, Double weekDayRate2Hour, Double weekDayRate3Hour, Double saturdayRate1Hour, Double saturdayRate2Hour, Double saturdayRate3Hour, Date saturdayStartTime, Date saturdayEndTime) {
    this.payStationId = payStationId;
    this.xLoc = xLoc;
    this.yLoc = yLoc;
    this.neighborhood = neighborhood;
    this.subArea = subArea;
    this.side = side;
    this.unitDescription = unitDescription;
    this.payByPhone = payByPhone;
    this.weekDayRate1Hour = weekDayRate1Hour;
    this.weekDayRate2Hour = weekDayRate2Hour;
    this.weekDayRate3Hour = weekDayRate3Hour;
    SaturdayRate1Hour = saturdayRate1Hour;
    SaturdayRate2Hour = saturdayRate2Hour;
    SaturdayRate3Hour = saturdayRate3Hour;
    this.saturdayStartTime = saturdayStartTime;
    this.saturdayEndTime = saturdayEndTime;
  }

  // This constructor can be used for reading records from MySQL, where we only have the payStationId,
  // such as a foreign key reference to payStationId.
  // Given payStationId, we can fetch the full payStation record.
  public PayStations(int payStationId) {
    this.payStationId = payStationId;
  }


  // This constructor can be used for creating new records, where the payStationId may not be
  // assigned yet since it is auto-generated by MySQL.
  public PayStations(Double xLoc, Double yLoc, String neighborhood, String subArea, String side, String unitDescription, int payByPhone, Double weekDayRate1Hour, Double weekDayRate2Hour, Double weekDayRate3Hour, Double saturdayRate1Hour, Double saturdayRate2Hour, Double saturdayRate3Hour, Date saturdayStartTime, Date saturdayEndTime) {
    this.xLoc = xLoc;
    this.yLoc = yLoc;
    this.neighborhood = neighborhood;
    this.subArea = subArea;
    this.side = side;
    this.unitDescription = unitDescription;
    this.payByPhone = payByPhone;
    this.weekDayRate1Hour = weekDayRate1Hour;
    this.weekDayRate2Hour = weekDayRate2Hour;
    this.weekDayRate3Hour = weekDayRate3Hour;
    SaturdayRate1Hour = saturdayRate1Hour;
    SaturdayRate2Hour = saturdayRate2Hour;
    SaturdayRate3Hour = saturdayRate3Hour;
    this.saturdayStartTime = saturdayStartTime;
    this.saturdayEndTime = saturdayEndTime;
  }


  public int getPayStationId() {
    return payStationId;
  }

  public void setPayStationId(int payStationId) {
    this.payStationId = payStationId;
  }

  public Double getxLoc() {
    return xLoc;
  }

  public void setxLoc(Double xLoc) {
    this.xLoc = xLoc;
  }

  public Double getyLoc() {
    return yLoc;
  }

  public void setyLoc(Double yLoc) {
    this.yLoc = yLoc;
  }

  public String getNeighborhood() {
    return neighborhood;
  }

  public void setNeighborhood(String neighborhood) {
    this.neighborhood = neighborhood;
  }

  public String getSubArea() {
    return subArea;
  }

  public void setSubArea(String subArea) {
    this.subArea = subArea;
  }

  public String getSide() {
    return side;
  }

  public void setSide(String side) {
    this.side = side;
  }

  public String getUnitDescription() {
    return unitDescription;
  }

  public void setUnitDescription(String unitDescription) {
    this.unitDescription = unitDescription;
  }

  public int getPayByPhone() {
    return payByPhone;
  }

  public void setPayByPhone(int payByPhone) {
    this.payByPhone = payByPhone;
  }

  public Double getWeekDayRate1Hour() {
    return weekDayRate1Hour;
  }

  public void setWeekDayRate1Hour(Double weekDayRate1Hour) {
    this.weekDayRate1Hour = weekDayRate1Hour;
  }

  public Double getWeekDayRate2Hour() {
    return weekDayRate2Hour;
  }

  public void setWeekDayRate2Hour(Double weekDayRate2Hour) {
    this.weekDayRate2Hour = weekDayRate2Hour;
  }

  public Double getWeekDayRate3Hour() {
    return weekDayRate3Hour;
  }

  public void setWeekDayRate3Hour(Double weekDayRate3Hour) {
    this.weekDayRate3Hour = weekDayRate3Hour;
  }

  public Double getSaturdayRate1Hour() {
    return SaturdayRate1Hour;
  }

  public void setSaturdayRate1Hour(Double saturdayRate1Hour) {
    SaturdayRate1Hour = saturdayRate1Hour;
  }

  public Double getSaturdayRate2Hour() {
    return SaturdayRate2Hour;
  }

  public void setSaturdayRate2Hour(Double saturdayRate2Hour) {
    SaturdayRate2Hour = saturdayRate2Hour;
  }

  public Double getSaturdayRate3Hour() {
    return SaturdayRate3Hour;
  }

  public void setSaturdayRate3Hour(Double saturdayRate3Hour) {
    SaturdayRate3Hour = saturdayRate3Hour;
  }

  public Date getSaturdayStartTime() {
    return saturdayStartTime;
  }

  public void setSaturdayStartTime(Date saturdayStartTime) {
    this.saturdayStartTime = saturdayStartTime;
  }

  public Date getSaturdayEndTime() {
    return saturdayEndTime;
  }

  public void setSaturdayEndTime(Date saturdayEndTime) {
    this.saturdayEndTime = saturdayEndTime;
  }
}
