package model;

public class Ratings {

//  RatingId INT AUTO_INCREMENT,
//  Rating INT,
//  UserName VARCHAR(255),
//  ParkingId INT,

  protected int ratingId;
  protected int rating;
  protected String userName;
  protected int parkingId;

  // This constructor can be used for reading records from MySQL, where we have all fields,
  // including the ratingId.
  public Ratings(int ratingId, int rating, String userName, int parkingId) {
    this.ratingId = ratingId;
    this.rating = rating;
    this.userName = userName;
    this.parkingId = parkingId;
  }


  // This constructor can be used for reading records from MySQL, where we only have the ratingId,
  // such as a foreign key reference to ratingId.
  // Given ratingId, we can fetch the full ratings record.
  public Ratings(int ratingId) {
    this.ratingId = ratingId;
  }

  // This constructor can be used for creating new records, where the ratingId may not be
  // assigned yet since it is auto-generated by MySQL.
  public Ratings(int rating, String userName, int parkingId) {
    this.rating = rating;
    this.userName = userName;
    this.parkingId = parkingId;
  }

  public int getRatingId() {
    return ratingId;
  }

  public void setRatingId(int ratingId) {
    this.ratingId = ratingId;
  }

  public int getRating() {
    return rating;
  }

  public void setRating(int rating) {
    this.rating = rating;
  }

  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public int getParkingId() {
    return parkingId;
  }

  public void setParkingId(int parkingId) {
    this.parkingId = parkingId;
  }
}
