package model;

public class Severity {

//  SeverityId INT AUTO_INCREMENT,
//  SeverityCode INT,
//  SeverityDesc VARCHAR(255),

  protected int severityId;
  protected int severityCode;
  protected String severityDesc;


  // This constructor can be used for reading records from MySQL, where we have all fields,
  // including the severityId.
  public Severity(int severityId, int severityCode, String severityDesc) {
    this.severityId = severityId;
    this.severityCode = severityCode;
    this.severityDesc = severityDesc;
  }

  // This constructor can be used for reading records from MySQL, where we only have the severityId,
  // such as a foreign key reference to severityId.
  // Given severityId, we can fetch the full Severity record
  public Severity(int severityId) {
    this.severityId = severityId;
  }


  // This constructor can be used for creating new records, where the severityCode may not be
  // assigned yet since it is auto-generated by MySQL.
  public Severity(int severityCode, String severityDesc) {
    this.severityCode = severityCode;
    this.severityDesc = severityDesc;
  }

  public int getSeverityId() {
    return severityId;
  }

  public void setSeverityId(int severityId) {
    this.severityId = severityId;
  }

  public int getSeverityCode() {
    return severityCode;
  }

  public void setSeverityCode(int severityCode) {
    this.severityCode = severityCode;
  }

  public String getSeverityDesc() {
    return severityDesc;
  }

  public void setSeverityDesc(String severityDesc) {
    this.severityDesc = severityDesc;
  }
}
